name: ex1
on: 
  workflow_dispatch:
               
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      vitest-path: ${{ steps.set-output.outputs.vitest-path }} 
    steps: 
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - run: npm install
      - id: set-output
        run: echo "vitest-path=$(pwd)" >> $GITHUB_ENV 
      - id: output-step
        run: echo "::set-output name=vitest-path::$(pwd)"
        
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - run: npm test
      - name: Show Output
        run: echo "Path is ${{ needs.job1.outputs.vitest-path }}" 
   

