name: ex1
on: 
  workflow_dispatch:
               
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name : setup node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: run install
        shell: bash
        run: |
          npm install 
          npm test
