env: 
  NODE_VERSION : '20'
name: Switch Node version
on: 
  pull_request:

jobs:
  run-npm-test:
    runs-on: ubuntu-latest
    steps:
        - name: checkout
          uses: actions/checkout@v4
        - name : setup node
          uses: actions/setup-node@v4
          with:
            node-version: '$NODE_VERSION'
        - name: run version
          shell: bash
          run: |
            node -v
          
