name: Switch Node version
on: 
  pull_request:

env:
  NODE_VERSION: '20'  
  REPO_OWNER: 'cellou59'
  REPO_NAME: 'github-action'
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


jobs:
  run-npm-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Run Node Version
        shell: bash
        run: |
          node -v

      - name: Create Fake Issue using Curl
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/issues \
            -d '{
              "title":"Found a bug",
              "body":"I'\''m having a problem with this.",
              "assignees":["octocat"], 
              "milestone":1,
              "labels":["bug"]
            }'
